apiVersion: apps/v1
kind: Deployment
metadata:
  name: tank-game
spec:
  replicas: 6
  selector:
    matchLabels:
      app: tank-game
  template:
    metadata:
      labels:
        app: tank-game
    spec:
      containers:
      - name: tank-game-container
        image: pururajchoudhary23/tankvsalien:latest
        ports:
        - containerPort: 80
